ALTER TABLE REGIONS ADD(
    CONSTRAINT REG_ID_PK PRIMARY KEY(REGION_ID)
);

ALTER TABLE COUNTRIES ADD(
    CONSTRAINT COUNTR_REG_FK FOREIGN KEY(REGION_ID) REFERENCES REGIONS(REGION_ID)
);

ALTER TABLE COUNTRIES ADD(
    CONSTRAINT COUNTR_ID_PK PRIMARY KEY(COUNTRY_ID)
);

ALTER TABLE LOCATIONS ADD(
    CONSTRAINT LOC_ID_PK PRIMARY KEY(LOCATION_ID),
    CONSTRAINT LOC_COUNTR_FK FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
);

ALTER TABLE DEPARTMENTS ADD(
    CONSTRAINT DEPT_ID_PK PRIMARY KEY(DEPARTMENT_ID),
    CONSTRAINT DEPT_LOC_FK FOREIGN KEY(LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

ALTER TABLE JOBS ADD(
    CONSTRAINT JOB_ID_PK PRIMARY KEY(JOB_ID)
);

ALTER TABLE EMPLOYEES ADD(
    CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY(EMPLOYEE_ID),
    CONSTRAINT EMP_EMP_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    CONSTRAINT EMP_MAN_FK FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

ALTER TABLE DEPARTMENTS ADD(
    CONSTRAINT DEPT_MAN_FK FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

ALTER TABLE JOB_HISTORY ADD(
    CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY(EMPLOYEE_ID,START_DATE),
    CONSTRAINT JHIST_JOB_ID_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    CONSTRAINT JHIST_EMP_ID_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);
